version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loginform
    image: login:${TAG}
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
